import pyautogui
import time
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡰⠚⠉..⠉⠑⢦⠀⠀⠀⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠀⢠⠞⠀⠀⠀⠀⠀⠀⠀⠀⠱⡄⠀⠀")
print("        ⢀⠏  Rikesh  ⠹⡀ ")
print("⠀⠀⠀⠀⠀⠀⠀⠀⡜⠀⠀⠀⠀⠀⣀⣀⠀⠀⠀⠀⠀⢣⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⡇⠀⣠⠔⠋⠉⣩⣍⠉⠙⠢⣄⠀⢸⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⢧⡜⢏⠓⠒⠚⠁⠈⠑⠒⠚⣹⢳⡸⠀")
print("⠀⠀⠀⠀⠀⠀⠀⠀⠘⣆⠸⡄⠀⠀⠀⠀⠀⠀⢠⠇⣰⠃⠀")
print("⠀⠀⠀⠀⠀⠀⢀⡴⠚⠉⢣⡙⢦⡀⠀⠀⢀⡰⢋⡜⠉⠓⠦⣀⠀⠀⠀⠀  __  __   _____        __  __               _       _    _                  _")
print("⠀⠀⠀⠀⠀⡴⠁⢀⣀⣀⣀⣙⣦⣉⣉⣋⣉⣴⣋⣀⣀⣀⡀⠈⢧⠀   |  \/  | |  __ \      |  \/  |             | |     | |  | |                | |")
print("⠀⠀⠀⠀⡸⠁⠀⢸⠀⠀⠀⠀⢀⣔⡛⠛⡲⡀⠀⠀⠀⠀⡇⠀⠈⢇⠀⠀ | \  / | | |__) |     | \  / |   __ _    __| |     | |__| |   __ _    ___  | | __   ___   _ __")
print("⠀⠀⠀⢠⠇⠀⠀⠸⡀⠀⠀⠀⠸⣼⠽⠯⢧⠇⠀⠀⠀⠀⡇⠀⠀⠘⡆⠀ | |\/| | |  _  /      | |\/| |  / _` |  / _` |     |  __  |  / _` |  / __| | |/ /  / _ \ | '__|")
print("⠀⠀⠀⣸⠀⠀⠀⠀⡇⠀⠀⠀⠳⢼⡦⢴⡯⠞⠀⠀⠀⢰⠀⠀⠀⠀⢧  | |  | | | | \ \   _  | |  | | | (_| | | (_| |  _  | |  | | | (_| | | (__  |   <  |  __/ | |")
print("⠀⠀⠀⢻⠀⠀⠀⠀⡇⠀⠀⠀⢀⡤⠚⠛⢦⣀⠀⠀⠀⢸⠀⠀⠀⠀⡼⠀⠀|_|  |_| |_|  \_\ (_) |_|  |_|  \__,_ | \__,_| (_) |_|  |_|  \__,_|  \___| |_|\_\  \___| |_|   RIKESH DAHAL")
print("   ⠈⠳⠤⠤⣖⣓RIKESH DAHAL⣒⣚⣲⠤⠤")
time.sleep(1.0)
pyautogui.hotkey('win')
time.sleep(0.5)
pyautogui.typewrite("virus & threat protection", interval=0.02)
pyautogui.hotkey('enter')
time.sleep(3.0)
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
pyautogui.hotkey('tab')
time.sleep(0.2)
pyautogui.hotkey('enter')
time.sleep(0.2)
pyautogui.hotkey('space')
time.sleep(4)
pyautogui.hotkey('alt','y')
